name: 'Arduino Continuous Deployment'
description: 'OTA Update via MQTT and HTTP for Arduino'
inputs:
  deviceId:
    description: 'To be deployed device id'
    required: true
    default: '0'
  binaryPath:
    description: 'Path to binary file'
    required: false
    default: '/home/runner/sketch/build/'
outputs:
  result:
    description: 'Deployment result'
runs:
  using: 'node16'
  main: 'dist/index.js'
