name: 'Node MCU Continuous Deployment'
description: 'Greet someone and record the time'
inputs:
  githubWorkspace: # id of input
    description: 'GitHub Workspace Directory'
    required: true
    default: '.'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
