name: 'Node MCU Continuous Deployment'
description: 'Greet someone and record the time'
inputs:
  deviceId:
    description: 'To be deployed device id'
    required: true
    default: '0'
outputs:
  result:
    description: 'Deployment result'
runs:
  using: 'node16'
  main: 'dist/index.js'
