on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Node MCU CD
    steps:
      - name: Deploy
        id: cd
        uses: potaesm/github-actions-node-mcu-cd@1.1.4
        with:
          deviceId: '0'
      # Use the output from the `cd` step
      - name: Get Result
        run: echo "The deployment was ${{ steps.cd.outputs.result }}"
