on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Node MCU Deploy
    steps:
      - name: checking out repo
        uses: actions/checkout@v2
      - name: build and deploy
        id: cd
        uses: potaesm/github-actions-node-mcu-cd@1.1.3
        with:
          githubWorkspace: ${{ github.workspace }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.cd.outputs.time }}"
