on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Node MCU Build & Deploy
    steps:
      - name: Check out repo
        uses: actions/checkout@v2.5.0
      - name: Compile .ino
        uses: ArminJo/arduino-test-compile@v3
        with:
          sketch-names: sketch.ino
          sketch-names-find-start: Sketches/
          arduino-board-fqbn: esp8266:esp8266:nodemcuv2
          platform-default-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
          set-build-path: true
      - name: Binary Lookup
        run: |
          cd /home/runner/sketch/build/
          ls -la
      - name: Deploy
        id: deployment
        uses: potaesm/github-actions-node-mcu-cd@v1.0.1
        with:
          deviceId: 'SSS'
      - name: Get Result
        run: echo "The deployment was ${{ steps.deployment.outputs.result }}"
      # - name: Install Arduino ClI
      #   run: |
      #     curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh -s 0.9.0
      #     ./bin/arduino-cli config init --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
      #     ./bin/arduino-cli core update-index
      #     ./bin/arduino-cli core install esp8266:esp8266
      #     ./bin/arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 ${{ github.workspace }}/sketch.ino --output sketch.bin -v
      #     ls -la
