on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Node MCU CD
    steps:
      - name: Check out repo
        uses: actions/checkout@v2.5.0
      - name: Compile .ino
        uses: ArminJo/arduino-test-compile@v3
        with:
          sketch-names: sketch.ino
          sketch-names-find-start: Sketches/
          arduino-board-fqbn: esp8266:esp8266:nodemcuv2
          platform-default-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
          set-build-path: true
      - name: Binary Lookup
        run: |
          cd Sketches
          ls -la
      # - name: Install Arduino ClI
      #   run: |
      #     curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh -s 0.9.0
      #     ./bin/arduino-cli config init --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
      #     ./bin/arduino-cli core update-index
      #     ./bin/arduino-cli core install esp8266:esp8266
      #     ./bin/arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 ${{ github.workspace }}/sketch.ino --output sketch.bin -v
      #     ls -la
      # - name: Deploy
      #   id: cd
      #   uses: potaesm/github-actions-node-mcu-cd@1.1.4
      #   with:
      #     deviceId: '0'
      # # Use the output from the `cd` step
      # - name: Get Result
      #   run: echo "The deployment was ${{ steps.cd.outputs.result }}"
